-- Test Users for GUTMANN System
-- Passwords are bcrypt hashes (12 rounds) generated by scripts/generate-bcrypt-hashes.js
-- Run this in Supabase SQL Editor after the schema migrations.
--
-- Password legend:
--   ceo@gutmann.com        -> Admin@12345
--   sales@gutmann.com      -> Sales@12345
--   qc@gutmann.com         -> Qc@12345
--   technical@gutmann.com  -> Tech@12345
--   estimation@gutmann.com -> Est@12345
--
-- Regenerate hashes at any time:
--   cd <repo-root> && node scripts/generate-bcrypt-hashes.js

-- pgcrypto provides gen_random_uuid(); safe to run even if already enabled.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- CEO
INSERT INTO public.users (id, email, password_hash, name, role, is_active, created_at, updated_at)
SELECT
  gen_random_uuid(),
  'ceo@gutmann.com',
  '$2a$12$hIEEFP/ftW2ySV/.TwsCj.GPkqrnJFA57la2LAN61m7307/cbQsxa',
  'Ahmad Al-Rashid',
  'ceo',
  true,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.users WHERE email = 'ceo@gutmann.com'
);

-- Salesperson
INSERT INTO public.users (id, email, password_hash, name, role, is_active, created_at, updated_at)
SELECT
  gen_random_uuid(),
  'sales@gutmann.com',
  '$2a$12$6bFwE.s1zkitvjm2jeasguToA.9uXDKYU74oy4vlMZGoqzhExkhda',
  'Sara Malik',
  'salesperson',
  true,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.users WHERE email = 'sales@gutmann.com'
);

-- QC
INSERT INTO public.users (id, email, password_hash, name, role, is_active, created_at, updated_at)
SELECT
  gen_random_uuid(),
  'qc@gutmann.com',
  '$2a$12$OlI/v/f1pguac6mdY9/Kku6cmtlA0/YF1MOLt73vz9pEjIShUisz6',
  'Fatima Zahra',
  'qc',
  true,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.users WHERE email = 'qc@gutmann.com'
);

-- Technical
INSERT INTO public.users (id, email, password_hash, name, role, is_active, created_at, updated_at)
SELECT
  gen_random_uuid(),
  'technical@gutmann.com',
  '$2a$12$EI4J3zILpyy8kVnacM0/jeVSGZSKteRX5OSxsxXNg.g2eXr3WtO5O',
  'Khalid Ibrahim',
  'technical',
  true,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.users WHERE email = 'technical@gutmann.com'
);

-- Estimation
INSERT INTO public.users (id, email, password_hash, name, role, is_active, created_at, updated_at)
SELECT
  gen_random_uuid(),
  'estimation@gutmann.com',
  '$2a$12$6zkLbpPF6wGyPbL2YlcmSu3sxY3WOjfvmJHngl9BWjxeuJuYvb2Wu',
  'Nadia Hassan',
  'estimation',
  true,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.users WHERE email = 'estimation@gutmann.com'
);

-- Verify inserted rows
SELECT id, email, name, role, is_active, created_at
FROM public.users
WHERE email IN (
  'ceo@gutmann.com',
  'sales@gutmann.com',
  'qc@gutmann.com',
  'technical@gutmann.com',
  'estimation@gutmann.com'
)
ORDER BY
  CASE role
    WHEN 'ceo'         THEN 1
    WHEN 'salesperson' THEN 2
    WHEN 'qc'          THEN 3
    WHEN 'technical'   THEN 4
    WHEN 'estimation'  THEN 5
  END;
