#!/usr/bin/env python3
"""
generate_password_hash.py
=========================
Generates bcrypt password hashes (12 rounds) that are compatible with the
Gutmann backend (uses bcryptjs with saltRounds=12).

Usage
-----
# Install dependency once (Python standard library does not include bcrypt):
    pip install bcrypt

# Hash a single password:
    python scripts/generate_password_hash.py MyPassword123

# Hash the default set of test-user passwords (no arguments):
    python scripts/generate_password_hash.py

# Running in GitHub Codespaces terminal:
    pip install bcrypt && python scripts/generate_password_hash.py

# Running in a Render shell (open via Render dashboard → your backend service → Shell):
    pip install bcrypt && python scripts/generate_password_hash.py

Output
------
The script prints each plaintext → bcrypt hash pair AND a ready-to-run
Supabase SQL block that you can paste directly into
  Supabase Dashboard → SQL Editor → New query → Run
"""

import sys
import textwrap

try:
    import bcrypt
except ImportError:
    print("ERROR: 'bcrypt' package not installed.")
    print("Run:  pip install bcrypt")
    sys.exit(1)

SALT_ROUNDS = 12  # Must match backend AuthController.js: bcrypt.hash(password, 12)

# Default test users  (email, plaintext_password, name, role)
DEFAULT_USERS = [
    ("ceo@gutmann.com",         "Admin@12345",  "CEO Admin",        "ceo"),
    ("sales@gutmann.com",       "Sales@12345",  "Sales User",       "salesperson"),
    ("qc@gutmann.com",          "Qc@12345",     "QC User",          "qc"),
    ("technical@gutmann.com",   "Tech@12345",   "Technical User",   "technical"),
    ("estimation@gutmann.com",  "Est@12345",    "Estimation User",  "estimation"),
]


def hash_password(plaintext: str) -> str:
    """Return a bcrypt hash of *plaintext* using SALT_ROUNDS."""
    return bcrypt.hashpw(plaintext.encode("utf-8"), bcrypt.gensalt(SALT_ROUNDS)).decode("utf-8")


def build_sql(users_with_hashes: list) -> str:
    """Build a Supabase-compatible SQL INSERT block."""
    lines = [
        "-- Auto-generated by scripts/generate_password_hash.py",
        "-- Run this in: Supabase Dashboard → SQL Editor → New query → Run",
        "",
        "create extension if not exists pgcrypto;",
        "",
    ]
    for email, _plain, name, role, hashed in users_with_hashes:
        escaped_hash = hashed.replace("'", "''")
        block = textwrap.dedent(f"""\
            insert into public.users
              (id, email, password_hash, name, role, is_active, created_at, updated_at)
            select
              gen_random_uuid(),
              '{email}',
              '{escaped_hash}',
              '{name}',
              '{role}',
              true,
              now(),
              now()
            where not exists (select 1 from public.users where email = '{email}');
        """)
        lines.append(block)

    emails = ", ".join(f"'{e}'" for e, *_ in users_with_hashes)
    lines += [
        "-- Verify",
        f"select email, name, role, is_active, created_at",
        f"from public.users",
        f"where email in ({emails})",
        "order by email;",
    ]
    return "\n".join(lines)


def main():
    if len(sys.argv) > 1:
        # Single-password mode
        plaintext = sys.argv[1]
        hashed = hash_password(plaintext)
        print(f"\nPlaintext : {plaintext}")
        print(f"Hash      : {hashed}")
        print("\nPaste this hash into the password_hash column in your SQL INSERT.")
    else:
        # Batch mode — hash all default test users
        print(f"\nGenerating bcrypt hashes (rounds={SALT_ROUNDS}). This takes a few seconds ...\n")
        results = []
        for email, plain, name, role in DEFAULT_USERS:
            hashed = hash_password(plain)
            results.append((email, plain, name, role, hashed))
            print(f"  {email}")
            print(f"    password : {plain}")
            print(f"    hash     : {hashed}\n")

        sql = build_sql(results)
        separator = "=" * 70
        print(separator)
        print("SUPABASE SQL (copy everything between the lines and run it)")
        print(separator)
        print(sql)
        print(separator)
        print("\nSteps:")
        print("  1. Copy the SQL block above.")
        print("  2. Open Supabase Dashboard → SQL Editor → New query.")
        print("  3. Paste and click 'Run'.")
        print("  4. Log in at your backend URL:")
        print("       POST /api/auth/login  { \"email\": \"ceo@gutmann.com\", \"password\": \"Admin@12345\" }")


if __name__ == "__main__":
    main()
